Removed error variable in steps, replaced by echo statment. Also made sure scripts and steps return the correct 0/1 value

diff --git a/bin/ec2-create b/bin/ec2-create
--- a/bin/ec2-create
+++ b/bin/ec2-create
@@ -14,8 +14,17 @@ while getopts :a:k:s:g opt; do
 		k) KEYPAIR=$OPTARG;;
 		s) EC2_SIZE=$OPTARG;;
 		g) SEC_GROUP=$OPTARG;;
-		\?) echo "Invalid option: -$opt"; echo "Usage ec2-create [-aksg]";;
+		\?) echo "Invalid option: -$opt"; echo "Usage ec2-create [-aksg]"; exit 1;;
 	esac
 done
 
-ec2-run-instances $AMI -k $KEYPAIR --instance-type $EC2_SIZE -g $SEC_GROUP | grep INSTANCE | awk '{ split( $0, a, " "); print a[2] }'
+ec2-run-instances $AMI -k $KEYPAIR --instance-type $EC2_SIZE -g $SEC_GROUP > $curr_dir/ec2-create.out
+ret=$?
+if [ $ret -ne 0 ]; then
+	cat $curr_dir/ec2-create.out
+	rm $curr_dir/ec2-create.out
+	exit $ret
+fi 
+cat $curr_dir/ec2-create.out | grep INSTANCE | awk '{ split( $0, a, " "); print a[2] }'
+rm $curr_dir/ec2-create.out 
+exit 0
diff --git a/bin/vm-check b/bin/vm-check
--- a/bin/vm-check
+++ b/bin/vm-check
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+curr_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
 SSH_KEY=~/.ssh/id_rsa
 
 while getopts :i opt; do
@@ -13,16 +15,17 @@ if [ $# -lt 3 ]; then
 	echo "Usage vm-install [-i <ssh_key>] <host> <user> <module>"
 	exit 1
 fi
-	
-module=${@:$(($#))}
-user=${@:$(($#-1))}
-host=${@:$(($#-2))}
+
+args=${@:$(($#-2))}
+module=`echo $args | awk '{ split($0, a, " "); print a[3] }'`
+user=`echo $args | awk '{ split($0, a, " "); print a[2] }'`
+host=`echo $args | awk '{ split($0, a, " "); print a[1] }'`
 
 if [ ! -e $curr_dir/../module/$module/check ]; then
-	echo "Uknown module '$module'"
+	echo "Can't find module '$module' check file $curr_dir/../module/$module/check"
 	exit 2
 else
 	scp -r $curr_dir/../module/$module $user@$host:/home/$user/.	
 	ssh -i $SSH_KEY $user@$host "/home/$user/$module/check"
 fi
-exit 0
+exit $?
